### ISSUE TITLE
Tag the Pay Wall Links

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [devanshbatham/Awesome-Bugbounty-Writeups#25]
Like 3 / 5 first links I clicked were to a Medium (i.e. paywall)

Would be fantastic to know which ones were hidden behind that wall before clicking 

Also ... didn't last long on it ... But the 1 link ... sure looked like it led to a p*rn site 

I did the cross site scripting then did the first like 5 links in a row (roughly)

**Comment by devanshbatham** [comment]
Hello @jacksonbrumbaugh, I understand that the links get outdated, and at this time I am the sole maintainer of this repo (along with many other repos). Due to low bandwidth, it is not always possible for me to review the links. 

I would appreciate if you can open a PR (filtering out any outdated URLs while you are going through the links). 

Thank you!

**Comment by jacksonbrumbaugh** [comment]
... still new to GitHub ... especially the interacting with ppl side ...

umm ... PR ... is that ... Pull Request?

is that easier / better to do on a PC?

or could I handle it okish on mobile?
